#!/bin/bash

# install gems
$gem update rake -v "0.8.2" --no-rdoc --no-ri --bindir=$bin_dir
$gem update sqlite3-ruby -v "1.2.2"  --no-rdoc --no-ri --bindir=$bin_dir
$gem update statarray -v "0.0.1" --no-rdoc --no-ri --bindir=$bin_dir
$gem update haml -v "2.0.3" --no-rdoc --no-ri --bindir=$bin_dir
$gem update thin -v "0.8.2" --no-rdoc --no-ri --bindir=$bin_dir
$gem update rjb -v "1.1.6"  --no-rdoc --no-ri --bindir=$bindir
$gem update rsruby -v "0.5"  -- --with-R-dir=$R_HOME --no-rdoc --no-ri --bindir=$bindir

$gem cleanup

