#!/bin/bash

# install openbabel
./configure --prefix=$prefix
make install

# install ruby bindings
cd $src/scripts/ruby
$ruby extconf.rb --with-openbabel-dir=$prefix --with-prefix=$prefix 
sed -i 's/Init_OpenBabel/Init_openbabel/' openbabel_ruby.cpp
make install
topdir=`grep 'topdir =' Makefile|sed 's/topdir = //'`
export RUBYLIB=$prefix/$topdir
