#!/bin/bash

# external plugins
mkdir -p $plugin_dir
cd $plugin_dir
git --git-dir=engines pull
git --git-dir=active_scaffold pull
git --git-dir=file_column pull
git --git-dir=exception_notification pull
cd $app_dir

# create haml plugin
vendor/bin/haml --rails .
