#!/bin/bash

git_url=http://opentox.org/git/ch

app_dir=`pwd`
prefix=$app_dir/vendor
bin_dir=$prefix/bin
src_dir=$prefix/src
gem_dir=$prefix/gems
plugin_dir=$prefix/plugins
r_home=$prefix/R

ruby=$bin_dir/ruby
gem=$bin_dir/gem
r_program=$bin_dir/R
rake=$bin_dir/rake

export PATH=$bin_dir:$PATH
export R_HOME=$r_home
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$R_HOME/bin
export GEM_HOME=$prefix/lib/ruby/gems/1.8
export RUBY=$ruby

