#!/bin/bash

# install openbabel
src=$src_dir/openbabel

# check the installed version to avoid recompilation
if ! ls -d $prefix/lib/openbabel/$version
then
	./configure --prefix=$prefix
	make
	make install

	# install ruby bindings
	cd $src/scripts/ruby
	$ruby extconf.rb --with-openbabel-dir=$prefix --with-prefix=$prefix 
	# fix wrong cases
	sed -i 's/Init_OpenBabel/Init_openbabel/' openbabel_ruby.cpp
	make
	make install
	topdir=`grep 'topdir =' Makefile|sed 's/topdir = //'`
	export RUBYLIB=$prefix/$topdir
fi
